name: Lingos Daily Auto

on:
  schedule:
    - cron: '30 21 * * *' # Odpala się codziennie o 23:30 czasu polskiego (okres letni)
  workflow_dispatch: # Przycisk do ręcznego uruchomienia w dowolnym momencie

jobs:
  run-lingos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python main.py
        env:
          LINGOS_USER: ${{ secrets.LINGOS_USER }}
          LINGOS_PASS: ${{ secrets.LINGOS_PASS }}
