name: Lingos Daily Auto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  run-lingos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Bot
        env:
          LINGOS_USER: ${{ secrets.LINGOS_USER }}
          LINGOS_PASS: ${{ secrets.LINGOS_PASS }}
        run: python main.py
