name: Lingos Daily Auto

on:
  workflow_dispatch:
  schedule:
    # 05:00 UTC = 07:00 czasu polskiego (w czasie letnim)
    # W czasie zimowym godzina 7:00 w Polsce to '0 6 * * *'
    - cron: '0 5 * * *'

jobs:
  run-lingos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 requests
          playwright install --with-deps chromium

      - name: Run script
        env:
          LINGOS_USER: ${{ secrets.LINGOS_USER }}
          LINGOS_PASS: ${{ secrets.LINGOS_PASS }}
        run: python main.py

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: '*.png'
